"""2

Revision ID: 641c3c35451b
Revises: db7bc5dab6e3
Create Date: 2019-02-24 00:02:24.836452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641c3c35451b'
down_revision = 'db7bc5dab6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
