"""4

Revision ID: ec0bb5f0508c
Revises: c34776689918
Create Date: 2019-02-24 14:51:18.292055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0bb5f0508c'
down_revision = 'c34776689918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
