"""5

Revision ID: e7926bc001f4
Revises: ec0bb5f0508c
Create Date: 2019-02-24 14:52:36.029188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7926bc001f4'
down_revision = 'ec0bb5f0508c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
