"""6

Revision ID: 4e25d5e98d83
Revises: e7926bc001f4
Create Date: 2019-02-24 23:07:14.857777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e25d5e98d83'
down_revision = 'e7926bc001f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('balance', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'balance')
    # ### end Alembic commands ###
