"""7

Revision ID: 276476227257
Revises: 4e25d5e98d83
Create Date: 2019-02-24 23:13:29.300907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276476227257'
down_revision = '4e25d5e98d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
